INSERT INTO TIPOSITUACAO (ID, DESCRICAO) values (1,'TIPO SITUACAO 1');
INSERT INTO TIPOSITUACAO (ID, DESCRICAO) values (2,'TIPO SITUACAO 2');

INSERT INTO SITUACAO (ID, DESCRICAO, TIPOSITUACAO_ID) values (1, 'SITUACAO 1.1', 1);
INSERT INTO SITUACAO (ID, DESCRICAO, TIPOSITUACAO_ID) values (2, 'SITUACAO 1.2', 1);
INSERT INTO SITUACAO (ID, DESCRICAO, TIPOSITUACAO_ID) values (3, 'SITUACAO 2.1', 2);